### ISSUE TITLE
Issue: Oauth2 client Fields jwks and jwks_uri can not both be set, you must choose one.

### ISSUE THREAD

**Issue by vdbulcke** [svrakitin/terraform-provider-hydra#5]
# Description 

When configuring `hydra_oauth2_client` with `jwks_uri`, the `jwks`  is also sent with the default value  `{"keys":null}` causing the following error from Hydra API: 

```
{"error":"invalid_client_metadata","error_description":"The value of one of the Client Metadata fields is invalid and the server has rejected this request. Note that an Authorization Server MAY choose to substitute a valid value for any requested parameter of a Client's Metadata. Fields jwks and jwks_uri can not both be set, you must choose one."}
```

## Workaround 

Explicitly specifying `jwk` works. 

### Hydra
* Get hydra lite for in memory db  (adapt binary version according to your architecture)
```
$ curl  -LO https://github.com/ory/hydra/releases/download/v2.0.3/hydra_2.0.3-linux_sqlite_64bit.tar.gz
$ tar xzf hydra_2.0.3-linux_sqlite_64bit.tar.gz
$ ./hydra version  
Version:    v2.0.3
Git Hash:   16831c55c41e64dd73637e8e2ca8f22202fc7d87
Build Time: 2022-12-08T11:54:38Z

```

* Create hydra config file `hydra.yaml`
```yaml
serve:
  cookies:
    same_site_mode: Lax


urls:
  self:
    issuer: http://127.0.0.1:4444
  consent: http://127.0.0.1:3000/consent
  login: http://127.0.0.1:3000/login
  logout: http://127.0.0.1:3000/logout

secrets:
  system:
    - youReallyNeedToChangeThis

## DB
dsn: memory

```

* start local hydra server 
```bash
./hydra serve all --config hydra.yaml --dev
```

### Terraform

```hcl
terraform {
  required_providers {
    hydra = {
      source = "svrakitin/hydra"
      version = "0.2.0"
    }
  }
}

# Configure the ORY Hydra Provider
provider "hydra" {
  endpoint = "http://localhost:4445"
}

# https://registry.terraform.io/providers/svrakitin/hydra/latest/docs/resources/oauth2_client
resource "hydra_oauth2_client" "example" {

    client_name = "example"
    client_secret  = "secret"
    metadata = {
        "first_party" = true
    }

    redirect_uris = [
        "http://127.0.0.1:5556/auth/callback"
    ]
    jwks_uri = "http://127.0.0.1:5556/jwk_uri"


    scopes         = ["offline", "openid"]
    grant_types    = ["refresh_token", "authorization_code"]
    response_types = [
        "code",
        "token", 
        "id_token"
    ]
    token_endpoint_auth_method = "client_secret_basic"

    subject_type               = "public"

}

```

## Version 
* Hydra: `v2.0.3` 
* Terraform `svrakitin/hydra` provider : `v0.2.0`
